import Head from 'next/head'
import Image from 'next/image'
import { createClient } from 'contentful';
import styles from '../styles/Home.module.css'

export async function getStaticProps(context) {
  const client = createClient({
    space: process.env.SPACE_ID,
    accessToken: process.env.ACCESS_TOKEN,
  });

  const query = {
    limit: 10,
    include: 10,
    content_type: 'recipe',
  };

  const { items } = await client.getEntries(query);

  return {
    props: {
      items
    }, // will be passed to the page component as props
  }
}

export default function Home({items}) {
  console.log(items);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Contentful API!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {
            items && items.map((item) => (
              <a href="https://nextjs.org/docs" className={styles.card} key={item.sys.id}>
                <h2>{item.fields.title}</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>

            ))
          }

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
